/*****************************************************************************
 * kbv busy animation
 * (C): G. Trauth, Erlangen
 * LastChangedDate: 2018-09-16
 * Created: 2011.12.04
 * This program is free software under the terms of the GNU General Public License,
 * either version 3 of the License, or (at your option) any later version.
 * For details see the GNU General Public License <http://www.gnu.org/licenses/>.
 * Terms of use (preloaders.net: ani_AnimatedBook, ani_InsideOut)
 * You are encouraged and legally entitled to copy and modify any animated GIF
 * and APNG images, generated by http://preloaders.net web-site. All animated
 * GIF and APNG images are completely free to use in all projects (web and
 * desktop applications, freeware and commercial projects).
 *****************************************************************************/
#include <QtDebug>
#include "kbvBusyAnimation.h"

KbvBusyAnimation::KbvBusyAnimation() : QWidget()
{
  ui.setupUi(this);

  busyAnim = new QMovie(":/kbv/icons/ani_AnimatedBook.gif");
  //qDebug() << "KbvBusyAnimation::KbvBusyAnimation valid" <<busyAnim->isValid(); //###########
  ui.aniLbl2->clear();
  ui.aniLbl3->clear();
  ui.aniButtonBox->hide();

  connect(ui.aniButtonBox, SIGNAL(rejected()), this, SLOT(buttonClicked()));
}

KbvBusyAnimation::~KbvBusyAnimation()
{
  //qDebug() << "KbvBusyAnimation::~KbvBusyAnimation"; //###########
  delete    busyAnim;
}
/****************************************************************************
 * run animation
 */
void    KbvBusyAnimation::run(QString title, bool run)
{
  //qDebug() << "KbvBusyAnimation::run" <<title <<run; //###########
  if(run)
    {
      name = title;
      ui.aniLbl1->setMovie(busyAnim);
      busyAnim->start();
    }
  else
    {
      ui.aniLbl1->clear();
      ui.aniLbl2->clear();
      ui.aniLbl3->clear();
    }
}
/****************************************************************************
 * Text 1
 */
void    KbvBusyAnimation::setText1(const QString text)
{
  ui.aniLbl2->setText(text);
}
/****************************************************************************
 * Text 2
 */
void    KbvBusyAnimation::setText2(const QString text)
{
  busyAnim->jumpToFrame(0);
  busyAnim->stop();
  ui.aniLbl3->setText(text);
  ui.aniButtonBox->show();
}
/****************************************************************************
 * Button
 */
void    KbvBusyAnimation::buttonClicked()
{
  //qDebug() << "KbvBusyAnimation::buttonClicked" << name; //###########
  emit  running(name, false);
}
/****************************************************************************/
